### ISSUE TITLE
First step of install steps is not clear where to check out repo

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-docker#9]
The first step in the README.md tells you to "clone the repository to your server". The second step tells you to go into `/var/intercity` and do some stuff. But that directory does not exist yet or contains the stuff you need to do.

Am I correct to assume that it's expected to clone this repository into `/var/intercity`?

**Comment by jvanbaarsen** [comment]
@michiels Yeah thats correct :)

**Comment by jvanbaarsen** [comment]
Fixed this in the parent project. Closing this issue.
